import { randomUUID } from 'node:crypto'
import { page, escape } from './pages.ts'
import type { Grant } from './control.ts'
import type { NodeRecord } from './store.ts'
const labels: Record<string,string> = { prepared:'维护已预留，等待监督器',executing:'维护执行中','local-review-required':'维护锁需本机核对',running:'运行中',completed:'已完成',failed:'失败',cancelled:'已取消','restart-required':'磁盘已安装，活动版本未确认，需受控重启','runtime-restarted':'新 Runtime 已上线，插件活动版本需核对','awaiting-runtime-verification':'等待新 Runtime 版本与连接验证','persistence-failed':'日志写入失败，操作已锁定','executor-recovery-required':'执行器需要本机核对','interrupted-review-required':'执行中断，需核对',active:'已启动',pending:'等待启动',loading:'加载中',healthy:'正常','plugin.install':'安装 / 更新插件','plugin.enable':'启用插件','plugin.disable':'停用插件','plugin.remove':'卸载插件','dsh.install':'安装 DSH','dsh.update':'更新 DSH','dsh.start':'启动 DSH','dsh.restart':'受控重启 DSH','dsh.stop':'停止 DSH','dsh.uninstall':'卸载 DSH' }
const label = (value: unknown) => labels[String(value)] ?? String(value ?? '未知')
const record = (value: unknown): Record<string,unknown> => value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string,unknown> : {}
const rows = (value: unknown): Record<string,unknown>[] => Array.isArray(value) ? value.map(record) : []
const hidden = (name: string, value: unknown) => `<input type="hidden" name="${escape(name)}" value="${escape(value)}">`
function action(text: string, method: string, fields: Record<string,unknown> = {}) {
  return `<form method="post">${hidden('method',method)}${'requestId' in fields ? '' : hidden('requestId',randomUUID())}${Object.entries(fields).map(([k,v])=>hidden(k,v)).join('')}<button>${escape(text)}</button></form>`
}
const details = (value: unknown) => `<details><summary>技术详情</summary><pre>${escape(JSON.stringify(value,null,2))}</pre></details>`
export function controlPage(id: string, name: string, inventory: {runtime: unknown; supervisor: unknown}): string {
  const runtime = record(inventory.runtime), supervisor = record(inventory.supervisor)
  const lifecycle = Array.isArray(supervisor.runtimeLifecycle)
  const plugins = rows(runtime.plugins), bundles = rows(runtime.bundles)
  const jobs = [...rows(runtime.jobs),...rows(supervisor.jobs)].sort((a,b)=>Number(b.createdAt)-Number(a.createdAt))
  return page('节点管理', `<h1>${escape(name)} · 节点管理</h1><nav><a href="/">返回节点</a><a href="/control/grants">节点授权</a><a href="/control/audit">审计</a><a href="/control/${id}">刷新状态</a></nav>
<section class="card"><h2>运行状态</h2><dl><dt>Runtime</dt><dd>${runtime.version ? escape(runtime.version) : '离线或不支持管理'}</dd><dt>生命周期监督器</dt><dd>${lifecycle?'在线':'离线；DSH 安装、更新与启停不可用'}</dd><dt>维护状态</dt><dd>${escape(label(record(runtime.maintenance ?? supervisor.maintenance).phase ?? '空闲'))}</dd><dt>Runtime 日志</dt><dd>${escape(label(runtime.persistence))}</dd><dt>监督器日志</dt><dd>${escape(label(supervisor.persistence))}</dd></dl>${runtime.persistence === 'persistence-failed' ? action('重试写入 Runtime 日志','management.retry-persistence') : ''}${supervisor.persistence === 'persistence-failed' ? action('重试写入监督器日志','management.retry-persistence',{controller:'supervisor'}) : ''}</section>
<section class="card"><h2>插件</h2><table><thead><tr><th>插件</th><th>状态</th><th>操作</th></tr></thead><tbody>${plugins.map(p=>`<tr><td>${escape(p.moduleName)}</td><td>${p.enabled?'已启用':'已停用'} · ${escape(label(p.phase))}</td><td>${p.protected?'受保护':action(p.enabled?'停用':'启用','management.submit',{action:p.enabled?'plugin.disable':'plugin.enable',target:p.entryId})}</td></tr>`).join('')||'<tr><td colspan="3">Runtime 当前未提供插件清单。</td></tr>'}</tbody></table>
<h3>已安装包</h3><p>以下为磁盘版本；启用状态不证明活动代码版本。应用失败或待重启时，活动版本保持未验证。</p><table><thead><tr><th>包名</th><th>磁盘版本</th><th>操作</th></tr></thead><tbody>${bundles.map(p=>`<tr><td>${escape(p.name)}</td><td>${escape(p.version)}</td><td>${p.removable?action('卸载','management.submit',{action:'plugin.remove',target:p.name}):'受保护 / 非节点安装包'}</td></tr>`).join('')}</tbody></table>
<h3>安装或更新插件</h3><form method="post">${hidden('action','plugin.install')}${hidden('requestId',randomUUID())}<label>包名（需在节点的受信列表内）<input name="package" required></label><label>目标版本<input name="version" placeholder="1.2.3" required></label><nav><button name="method" value="management.check">检查版本</button><button name="method" value="management.submit">安装 / 更新</button></nav></form></section>
<section class="card"><h2>DSH 生命周期</h2>${lifecycle ? `<p>由独立监督器操作同一个 DSH 服务。存在活动任务或原生维护时拒绝执行，不自动取消；重启后验证新进程、连接代次和版本。停止不会关闭监督器；卸载保留本机配置与回滚材料。</p><form method="post">${hidden('requestId',randomUUID())}<label>操作<select name="action"><option value="dsh.update">更新 DSH</option><option value="dsh.install">首次安装 DSH</option></select></label><label>目标版本<input name="target" placeholder="0.1.7-rc.2" required></label><nav><button name="method" value="management.check">检查版本</button><button name="method" value="management.submit">执行</button></nav></form><nav>${action('启动 DSH','management.submit',{action:'dsh.start',target:'current'})}${action('受控重启 DSH','management.submit',{action:'dsh.restart',target:'current'})}${action('停止 DSH','management.submit',{action:'dsh.stop',target:'current'})}</nav><details><summary>卸载与故障恢复</summary>${action('卸载 DSH（保留配置）','management.submit',{action:'dsh.uninstall',target:'current'})}${action('恢复已退出进程的插件操作锁','management.recover')}<p>更新执行器可能有存活子进程时，必须在节点核对，不能仅凭 Gateway PID 删除锁。</p></details>`:'<p>请先在节点配置并启动独立监督服务。所有 DSH 生命周期动作均不会回退到 Runtime 内执行。</p>'}</section>
<section class="card"><h2>最近操作</h2><table><thead><tr><th>时间</th><th>动作</th><th>目标</th><th>状态</th><th>操作</th></tr></thead><tbody>${jobs.map(j=>`<tr><td>${escape(new Date(Number(j.createdAt)).toISOString())}</td><td>${escape(label(j.action))}</td><td>${escape(j.target)}</td><td>${escape(label(j.status))}${j.installedVersion?` · 磁盘版本 ${escape(j.installedVersion)}；活动版本 ${escape(j.activeVersion ?? '未验证')}`:''}</td><td>${j.status==='running' && j.action==='plugin.install'?action('取消安装','management.cancel',{requestId:j.id}):''}</td></tr>`).join('')||'<tr><td colspan="5">暂无操作记录。</td></tr>'}</tbody></table></section><section class="card"><h2>委派任务记录维护</h2><p>自动保留已结束任务 7 天。手动清理仅移除结束超过 24 小时的记录；运行任务及幂等窗口内记录始终保留。</p>${action('清理一天前已结束的任务记录','task.cleanup',{retentionMs:86400000})}</section>${details(inventory)}`)
}
export function grantsPage(grants: Grant[], nodes: NodeRecord[]): string {
  const name = (id:string) => nodes.find(n=>n.id===id)?.name ?? id
  const options = nodes.filter(n=>!n.revokedAt).map(n=>`<option value="${escape(n.id)}">${escape(n.name)}</option>`).join('')
  return page('节点授权',`<h1>节点定向授权</h1><a href="/">返回节点</a><p>默认拒绝。授权工作区是目标节点的工作目录策略，不是文件系统沙箱。</p><section class="card"><table><thead><tr><th>来源 → 目标</th><th>工作区</th><th>到期</th><th>操作</th></tr></thead><tbody>${grants.map(g=>`<tr><td>${escape(name(g.source))} → ${escape(name(g.target))}</td><td>${escape(g.workspace)}</td><td>${escape(new Date(g.expiresAt).toISOString())}</td><td><form method="post">${hidden('revoke',g.id)}<button>立即撤销</button></form></td></tr>`).join('')||'<tr><td colspan="4">尚未授权节点间访问。</td></tr>'}</tbody></table></section><form method="post" class="card"><h2>添加授权</h2><label>来源节点<select name="source">${options}</select></label><label>目标节点<select name="target">${options}</select></label><label>目标授权工作区<input name="workspace" required></label><label>允许的操作<select name="capabilities"><option value="discover,task.start,task.read,task.cancel">发现节点、执行任务、读取结果、取消任务</option><option value="discover,task.read">发现节点与读取已有任务</option><option value="discover">仅发现节点</option></select></label><label>有效期<select name="durationSeconds"><option value="3600">1 小时</option><option value="86400">1 天</option><option value="604800">7 天</option><option value="2592000">30 天</option></select></label><button>添加授权</button></form>${details(grants)}`)
}
export function controlResult(result: unknown, id: string): string {
  const value = record(result)
  return page('操作结果',`<h1>操作已返回</h1><p>${escape(label(value.status ?? (value.availableVersion ? '目标版本可用' : '已受理，请刷新查看状态')))}</p>${value.availableVersion?`<p>可用版本：${escape(value.availableVersion)}</p>`:''}<a href="/control/${id}">返回节点，刷新状态</a>${details(result)}`)
}
