import type { NodeRecord } from './store.ts'

export function escape(value: unknown): string {
  return String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c] ?? c)
}
export function page(title: string, content: string, root = '/'): string {
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><title>${escape(title)} · DSH Hub</title><link rel="stylesheet" href="${escape(root)}hub.css"></head><body><header><a class="brand" href="${escape(root)}">DSH Hub</a><span>实验：节点控制 · Node control</span></header><main>${content}</main><footer>DSH Hub · 2.0.0-alpha.1 · node-control experiment</footer></body></html>`
}
export const css = `:root{color-scheme:light dark;font:16px/1.6 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#f5f6f8;color:#202630}*{box-sizing:border-box}body{margin:0}header,main,footer{max-width:920px;margin:auto;padding:24px}header{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #dce0e7}header span,footer,.muted{color:#667085;font-size:14px}.brand{font-size:20px;font-weight:700;color:inherit;text-decoration:none}h1{font-size:28px;margin:0 0 8px}h2{font-size:20px;margin:0 0 12px}p{margin:8px 0 20px}a{color:#2358b8}nav,.actions{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin:16px 0 24px}.card{padding:24px;background:white;border:1px solid #dde2ea;border-radius:12px;margin:16px 0}.node{display:flex;align-items:center;justify-content:space-between;gap:20px}.node h2{margin:0}.node p{margin:5px 0}.status{display:inline-block;font-size:13px;padding:2px 9px;border-radius:10px;background:#eef1f5;color:#667085}.online{background:#e8f7ee;color:#18733c}.danger{color:#b42318}.button,button{font:inherit;display:inline-block;border:1px solid #cad1de;background:white;color:#26354d;padding:9px 16px;border-radius:8px;text-decoration:none;cursor:pointer;white-space:nowrap}.primary{background:#275dcc;color:white;border-color:#275dcc}button:disabled{opacity:.5;cursor:not-allowed}input,select,textarea{font:inherit;border:1px solid #b8c2d1;background:white;color:inherit;border-radius:8px;padding:10px 12px;width:100%;max-width:560px}label{display:block;margin:16px 0 5px;font-weight:600}fieldset{border:0;padding:0;margin:0}pre{padding:16px;background:#101b2f;color:#e6eefb;white-space:pre-wrap;overflow-wrap:anywhere;border-radius:8px;font:13px/1.7 ui-monospace,monospace}code{overflow-wrap:anywhere}details{margin:12px 0}.error{background:#fff0ed;border-color:#f6c4ba}dl{display:grid;grid-template-columns:130px 1fr;gap:10px}dt{color:#667085}dd{margin:0;overflow-wrap:anywhere}footer{font-size:12px;padding-top:40px}@media(max-width:600px){header,main,footer{padding:18px}header span{display:none}h1{font-size:24px}.card{padding:18px}.node{align-items:flex-start}.node .button{padding:8px 12px}dl{grid-template-columns:90px 1fr}}@media(prefers-color-scheme:dark){:root{background:#11151c;color:#e2e8f1}header{border-color:#2b3442}.card,input,select,textarea,button,.button{background:#1b2230;border-color:#384253;color:#e2e8f1}.primary{background:#3871e0}.status{background:#2d3646;color:#adb9ca}.online{background:#18382a;color:#8ddab0}a{color:#98baff}.muted,header span,footer,dt{color:#9aa8ba}.error{background:#361e1e;border-color:#744139}}`

export function nodesPage(nodes: NodeRecord[], online: Set<string>): string {
  const active = nodes.filter(n => !n.revokedAt)
  const cards = active.map(n => `<article class="card node"><div><h2><a href="/nodes/${n.id}">${escape(n.name)}</a></h2><p><span class="status ${online.has(n.id) ? 'online' : ''}">${online.has(n.id) ? '在线' : '离线'}</span> <span class="muted">${n.mode === 'tailscale' ? 'Tailscale' : 'Tailcat'} · DSH ${escape(n.dshVersion)}</span></p></div>${online.has(n.id) ? `<a class="button primary" href="/open/${n.id}" target="_blank" rel="noopener">打开 DSH ↗</a>` : `<a class="button" href="/nodes/${n.id}">查看连接</a>`}</article>`).join('')
  return page('节点', `<h1>节点</h1><p class="muted">打开一台机器，使用它的原生 DSH。会话、模型和插件由各节点管理。</p><nav><a class="button primary" href="/invites/new">添加节点</a><a class="button" href="/network">连接设置</a><a class="button" href="/control/grants">节点授权</a><a class="button" href="/">刷新状态</a></nav>${cards || '<div class="card"><h2>连接你的第一台机器</h2><p>生成安装命令，在已有 DSH 的机器上执行，即可完成配对。</p></div>'}`)
}

export function failurePage(message: string, root = '/'): string {
  return page('连接提示', `<div class="card error"><h1>暂时无法打开</h1><p>${escape(message)}</p><a class="button" href="${escape(root)}">返回节点列表</a></div>`, root)
}
